// Code generated by "stringer -type=ObjectType ./object/"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INTEGER_OBJ-1]
	_ = x[BOOLEAN_OBJ-2]
	_ = x[NULL_OBJ-3]
	_ = x[RETURN_VALUE_OBJ-4]
	_ = x[ERROR_OBJ-5]
	_ = x[FUNCTION_OBJ-6]
	_ = x[STRING_OBJ-7]
	_ = x[BUILTIN_OBJ-8]
	_ = x[ARRAY_OBJ-9]
}

const _ObjectType_name = "INTEGER_OBJBOOLEAN_OBJNULL_OBJRETURN_VALUE_OBJERROR_OBJFUNCTION_OBJSTRING_OBJBUILTIN_OBJARRAY_OBJ"

var _ObjectType_index = [...]uint8{0, 11, 22, 30, 46, 55, 67, 77, 88, 97}

func (i ObjectType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ObjectType_index)-1 {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[idx]:_ObjectType_index[idx+1]]
}
