// Code generated by "stringer -type Type ./object/"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INTEGER-1]
	_ = x[BOOLEAN-2]
	_ = x[NULL-3]
	_ = x[RETURN_VALUE-4]
	_ = x[ERROR-5]
	_ = x[FUNCTION-6]
	_ = x[STRING-7]
	_ = x[BUILTIN-8]
	_ = x[ARRAY-9]
	_ = x[HASHMAP-10]
}

const _Type_name = "INTEGERBOOLEANNULLRETURN_VALUEERRORFUNCTIONSTRINGBUILTINARRAYHASHMAP"

var _Type_index = [...]uint8{0, 7, 14, 18, 30, 35, 43, 49, 56, 61, 68}

func (i Type) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
